from .base import FocusSignal, Profile


class VirtualCameraVusb(Profile):
    """Profile for libgphoto2's built-in virtual camera (the `vusb` port
    driver + `ptp2` camlib), for running the app without real hardware.

    Requires the vendored libgphoto2 fork build (scripts/bootstrap-gphoto2.sh);
    the vusb modifications are the "byzanz-capture patch NNNN" commits in
    `git -C vendor/libgphoto2 log`. With those the emulator coexists with a real USB
    camera in the same process AND exposes two independent virtual cameras,
    reported by autodetect as "Nikon DSC D750" on the `vusb:` and `vusb:2`
    ports. So a single instance can back one slot (e.g. IR) alongside a real
    body (VIS), or — with `VirtualCameraVusb2` pinned to `vusb:2` — both the
    visible and IR slots can run on the emulator with no hardware at all.
    The `port` ctor arg is what assigns an instance to a specific vusb port
    (they are otherwise indistinguishable — same model name).

    The emulator is deliberately minimal. What it does and does NOT do
    shapes every method below:
      * Capture works via trigger_capture(): it duplicates a JPEG seeded
        into its data dir (bootstrap's seed_vcamera) and emits FILE_ADDED +
        CAPTURE_COMPLETE — so the normal non-burst capture path applies.
      * Live view works via the normal Nikon PTP path (StartLiveView /
        GetLiveViewImg), added by fork patch 0005: the emulator
        streams the JPEGs in the source dir's liveview/ subdir (a looping
        drift animation generated by bootstrap's seed_liveview), or the
        capture seed image statically if that directory is absent. The
        app-side code path is identical to a real camera's.
      * The source dir is per-camera configurable at runtime
        (fork patch 0006): VCAMERADIR_<port-suffix> (VCAMERADIR_2 for
        the "vusb:2" instance) > VCAMERADIR > the compiled-in default,
        read at connect time — so VIS and IR can serve different test
        material. Both apps auto-point these vars at repo-local
        `vcamera-sources/vusb` / `vcamera-sources/vusb2` folders when
        they exist (see _gphoto2_paths.apply_vcamera_source_dirs);
        explicitly set env vars win. Seed files are re-stat'ed on every
        read: swapping capture/liveview images on disk mid-session (even
        with different file sizes) changes what the camera produces, no
        reconnect needed.
      * ISO / aperture / exposure time expose realistic enum ladders
        (fork patch 0007: ExposureIndex 100..12800, f/2.8..f/22, and
        the Nikon vendor exposure time 1/4000..30s + Time/Bulb in third
        stops with real-Nikon fraction labels), so the capture-setting
        dropdowns populate and behave like a real body's. The values are
        stored on the emulated camera but do NOT affect the produced
        images.
      * The focus magnifier works like on the production bodies: the
        profile maps the magnify button onto the real Nikon
        LiveViewImageZoomRatio property (fork patch 0009), and while
        it is on the emulator streams the seeded 1:1 center-crop
        sequence (liveview_zoom/, written by scripts/seed_vcam.py) —
        true sensor-resolution detail, like a real body magnifying.
      * It has no autofocus and no settable image format/quality. The
        lifecycle settings dicts are empty: writes to absent config keys
        are harmless (the worker's __try_set_config swallows them), but
        there's nothing real to set.
    """

    def __init__(self, port: str = "vusb:", name: str = "Virtual Camera (vusb)"):
        # `port` pins this profile to a specific vusb port. The patched
        # vendor build exposes two identical "Nikon DSC D750" cameras on
        # "vusb:" and "vusb:2" (see libgphoto2_port/vusb/vusb.c), so papyri
        # can run BOTH the visible and IR slots on the emulator by giving
        # each worker a different port — the model pattern alone can't tell
        # two identical virtual cameras apart.
        self._port = port
        self._name = name

    def name(self) -> str:
        return self._name

    def gphoto2_model_pattern(self) -> str:
        # The vcamera defaults to emulating a Nikon D750; autodetect reports
        # it as "Nikon DSC D750" (see libgphoto2_port/vusb/vusb.c).
        return "Nikon DSC D750"

    def gphoto2_port(self) -> str:
        return self._port

    def supports_live_view(self) -> bool:
        # The patched emulator (fork patch 0005) answers the full Nikon
        # liveview sequence, so the worker's normal preview loop just works.
        # NOTE: requires a vendor build with that patch; an unpatched vusb
        # would answer -6 on the first frame, which the worker handles by
        # stopping live view and refusing restarts until reconnect.
        return True

    def supports_autofocus(self) -> bool:
        return False

    def focus_magnify_property_name(self) -> str:
        # The real Nikon liveview-zoom property (0xD1A3), emulated by the
        # patched vusb driver (fork patch 0009); ptp2 exposes it as
        # this widget. Mirrors how the Sony profile names "focusmagnifier".
        return "liveviewimagezoomratio"

    def focus_magnify_value(self, on: bool) -> str:
        # Widget choice strings from ptp2's nikon_liveviewimagezoomratio
        # table. Every ratio > 0 serves the same seeded zoom sequence —
        # "100%" is the honest label for the 1:1 center crop.
        return "100%" if on else "Entire Display"

    def has_settable_aperture(self) -> bool:
        # The emulator answers the FNumber property with a realistic
        # f/2.8..f/22 enum (vendor patch 0007) and stores writes, so the
        # aperture dropdown populates and round-trips like a real body's —
        # cosmetic for the image, but it exercises the full UI plumbing.
        return True

    def burstnumber_property_name(self):
        # Unused: the emulator emits a clean per-trigger CAPTURE_COMPLETE and
        # has no `burstnumber` config, so no dome ever bursts it.
        return "burstnumber"

    def iso_property_name(self):
        return "iso"

    def shutterspeed_property_name(self):
        # "shutterspeed2" is the Nikon vendor exposure time (0xD100,
        # vendor patch 0007) with the fraction labels real Nikons show
        # ("1/250", "4/10", "2") — same widget the D800E/D90 profiles
        # bind. The generic "shutterspeed" widget (decimal "0.0100s"
        # labels) also exists but nothing binds it.
        return "shutterspeed2"

    def f_number_property_name(self):
        return "f-number"

    def image_format_property_name(self):
        return "imageformat"

    def poll_config(self):
        # The emulator's config is static — nothing useful to poll.
        return None

    def enable_capture_controls_in_live_preview(self) -> bool:
        return False

    def initial_settings(self):
        return {}

    def start_autofocus_settings(self):
        return {}

    def stop_autofocus_settings(self):
        return {}

    def focus_signal(self):
        # The emulator has no AF; the (empty) start settings return
        # instantly and that already counts as focused.
        return FocusSignal()

    def start_live_view_settings(self):
        return {}

    def stop_live_view_settings(self):
        return {}

    def start_capture_settings(self):
        return {}

    def stop_capture_settings(self):
        return {}

    def capture_format_jpeg_settings(self):
        return {}

    def capture_format_jpeg_and_raw_settings(self):
        return {}

    def capture_format_raw_settings(self):
        return {}
